services:
  activationbase:
    image: jishan900/activationbase_cardio_risk:latest
    volumes:
      - ai_system:/mnt
    command: sh -c "ls -R /tmp/activationBase && head -n 2 /tmp/activationBase/activation_data.csv"

volumes:
  ai_system:
    external: true
